### POST para criar um usuário
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "douglas@email.com",
  "name": "Douglas Neves",
  "password": "testpassword"
}

### GET para obter todos os usuários
GET http://localhost:3000/users

### GET para obter um usuário específico pelo ID
GET http://localhost:3000/users/1

### PUT para atualizar um usuário existente
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "email": "updated@example.com"
}

### DELETE para excluir um usuário pelo ID
DELETE http://localhost:3000/users/2


### Categoria
POST http://localhost:3000/category
Content-Type: application/json

{
  "name": "Doces"
}

### Obter todas as Categorias
GET http://localhost:3000/category

### Criação de um Produto 
POST http://localhost:3000/product
Content-Type: application/json

{
  "title": "Bala de Goma",
  "price": 1,
  "categoryID": 1
}

### Obter todos os Produtos
GET http://localhost:3000/product

### Atualização de um Produto 
PUT http://localhost:3000/product/:id
Content-Type: application/json

{
  "title": "Bala de Goma Atualizada"
}

### Exclusão de um Produto
DELETE http://localhost:3000/product/:id